pokemons = [
    # Geração 1 - Kanto
    "bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard",
    "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree",
    "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot",
    "rattata", "raticate", "spearow", "fearow", "ekans", "arbok",
    "pikachu", "raichu", "sandshrew", "sandslash", "nidoran-f", "nidorina",
    "nidoqueen", "nidoran-m", "nidorino", "nidoking", "clefairy", "clefable",
    "vulpix", "ninetales", "jigglypuff", "wigglytuff", "zubat", "golbat",
    "oddish", "gloom", "vileplume", "paras", "parasect", "venonat",
    "venomoth", "diglett", "dugtrio", "meowth", "persian", "psyduck",
    "golduck", "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra",
    "alakazam", "machop", "machoke", "machamp", "bellsprout", "weepinbell",
    "victreebel", "tentacool", "tentacruel", "geodude", "graveler", "golem",
    "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite", "magneton",
    "farfetch'd", "doduo", "dodrio", "seel", "dewgong", "grimer",
    "muk", "shellder", "cloyster", "gastly", "haunter", "gengar",
    "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb",
    "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee",
    "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon",
    "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen",
    "seaking", "staryu", "starmie", "mr. mime", "scyther", "jynx",
    "electabuzz", "magmar", "pinsir", "tauros", "magikarp", "gyarados",
    "lapras", "ditto", "eevee", "vaporeon", "jolteon", "flareon",
    "porygon", "omanyte", "omastar", "kabuto", "kabutops", "aerodactyl",
    "snorlax", "articuno", "zapdos", "moltres", "dratini", "dragonair",
    "dragonite", "mewtwo", "mew",

    # Geração 2 - Johto
    "chikorita", "bayleef", "meganium", "cyndaquil", "quilava", "typhlosion",
    "totodile", "croconaw", "feraligatr", "sentret", "furret", "hoothoot",
    "noctowl", "ledyba", "ledian", "spinarak", "ariados", "crobat",
    "chinchou", "lanturn", "pichu", "cleffa", "igglybuff", "togepi",
    "togetic", "natu", "xatu", "mareep", "flaaffy", "ampharos",
    "bellossom", "marill", "azumarill", "sudowoodo", "politoed", "hoppip",
    "skiploom", "jumpluff", "aipom", "sunkern", "sunflora", "wooper",
    "quagsire", "espeon", "umbreon", "murkrow", "slowking", "wobbuffet",
    "girafarig", "pineco", "forretress", "dunsparce", "gligar", "steelix",
    "snubbull", "granbull", "qwilfish", "scizor", "shuckle", "heracross",
    "sneasel", "teddiursa", "ursaring", "slugma", "magcargo", "swinub",
    "piloswine", "corsola", "remoraid", "octillery", "finneon", "lumineon",
    "surskit", "masquerain", "shroomish", "breloom", "slakoth", "vigoroth",
    "slaking", "nincada", "ninjask", "shedinja", "whismur", "loudred",
    "exploud", "makuhita", "hariyama", "azurill", "nosepass", "skitty",
    "delcatty", "sableye", "mawile", "aron", "lairon", "aggron",
    "meditite", "medicham", "electrike", "manectric", "plusle", "minun",
    "volbeat", "illumise", "roselia", "gulpin", "swallot", "carvanha",
    "sharpedo", "wailmer", "wailord", "numel", "camerupt", "torkoal",
    "spoink", "grumpig", "spheal", "sealeo", "walrein", "clamperl",
    "huntail", "gorebyss", "relicanth", "luvdisc", "bagon", "shelgon",
    "salamence", "beldum", "metang", "metagross", "registeel", "regirock",
    "regice", "latias", "latios", "kyogre", "groudon", "rayquaza",
    "jirachi", "deoxys",

    # Geração 3 - Hoenn
    "treecko", "grovyle", "sceptile", "torchic", "combusken", "blaziken",
    "mudkip", "mascoke", "swampert", "poochyena", "mightyena", "zigzagoon",
    "linoone", "wurmple", "silcoon", "beautifly", "cascoon", "dustox",
    "lotad", "lombre", "ludicolo", "seedot", "nuzleaf", "shiftry",
    "taillow", "swellow", "wingull", "pelipper", "ralts", "kirlia",
    "gardevoir", "surskit", "masquerain", "shroomish", "breloom", "slakoth",
    "vigoroth", "slaking", "nincada", "ninjask", "shedinja", "whismur",
    "loudred", "exploud", "makuhita", "hariyama", "azurill", "nosepass",
    "skitty", "delcatty", "sableye", "mawile", "aron", "lairon",
    "aggron", "meditite", "medicham", "electrike", "manectric", "plusle",
    "minun", "volbeat", "illumise", "roselia", "gulpin", "swallot",
    "carvanha", "sharpedo", "wailmer", "wailord", "numel", "camerupt",
    "torkoal", "spoink", "grumpig", "spheal", "sealeo", "walrein",
    "clamperl", "huntail", "gorebyss", "relicanth", "luvdisc", "bagon",
    "shelgon", "salamence", "beldum", "metang", "metagross", "registeel",
    "regirock", "regice", "latias", "latios", "kyogre", "groudon",
    "rayquaza", "jirachi", "deoxys",

    # Geração 4 - Sinnoh
    "turtwig", "grotle", "torterra", "chimchar", "monferno", "infernape",
    "piplup", "prinplup", "empoleon", "starly", "staravia", "staraptor",
    "bidoof", "bibarel", "kricketot", "kricketune", "shinx", "luxio",
    "luxray", "budew", "roserade", "cranidos", "rampardos", "shieldon",
    "bastiodon", "burmy", "wormadam", "mothim", "combee", "vespiquen", "pachirisu",
    "buizel", "floatzel", "cherubi", "cherrim", "shellos", "gastrodon",
    "ambipom", "drifloon", "drifblim", "buneary", "lopunny", "mismagius",
    "honchkrow", "glameow", "purugly", "chingling", "stunky", "skuntank",
    "bronzor", "bronzong", "bonsly", "mime-jr", "happiny", "chatot",
    "spiritomb", "gible", "gabite", "garchomp", "munchlax", "snorlax",
    "riolu", "lucario", "hippopotas", "hippowdon", "skorupi", "drapion",
    "croagunk", "toxicroak", "carnivine", "finneon", "lumineon", "snover",
    "abomasnow", "weavile", "magnezone", "lickilicky", "rhyperior", "tangrowth",
    "electivire", "magmortar", "togekiss", "yanmega", "leafeon", "glaceon",
    "sylveon", "porygon-z", "gardevoir", "mismagius", "giratina", "cresselia",
    "darkrai", "shaymin", "arceus",

    # Geração 5 - Unova
    " Victini", "snivy", "servine", "serperior", "tepig", "pignite",
    "emolga", "oshawott", "dewott", "samurott", "patrat", "watchog",
    "lillipup", "herdier", "stoutland", "purrloin", "liepard", "pansage",
    "simisage", "pansear", "simisear", "panpour", "simipour", "swadloon",
    "leavanny", "venipede", "whirlipede", "scolipede", "cottonee", "whimsicott",
    "petilil", "lilligant", "basculin", "sandile", "krokorok", "krookodile",
    "darumaka", "darmanitan", "maractus", "dwebble", "crustle", "scraggy",
    "scrafty", "sigilyph", "yamask", "cofagrigus", "tirtouga", "carracosta",
    "archen", "archaeops", "trubbish", "garbodor", "zorua", "zoroark",
    "minccino", "cinccino", "gothita", "gothorita", "gothitelle", "solgaleo",
    "salandit", "salazzle", "dartrix", "decidueye", "torracat", "incineroar",
    "rowlet", "litten", "litten", "lycanroc", "rockruff", "sableye",
    "mimikyu", "cosmoem", "cosmog", "naganadel", "buzzwole", "nihilego",
    "stakataka", "blacephalon", "zeraora", "meltan", "melmetal",

    # Geração 6 - Kalos
    "chespin", "quilladin", "chesnaught", "fennekin", "braixen", "delphox",
    "froakie", "frogadier", "greninja", "bunnelby", "diggersby", "fletchling",
    "fletchinder", "talonflame", "scatterbug", "spewpa", "vivillon", "litleo",
    "pyroar", "flabébé", "floette", "florges", "skiddo", "gogoat",
    "pancham", "pangoro", "furfrou", "espurr", "meowstic", "honedge",
    "doublade", "aegislash", "spritzee", "aromatisse", "swirlix", "slurpuff",
    "inkay", "malamar", "binacle", "barbaracle", "skrelp", "seadra",
    "clawitzer", "helioptile", "heliolisk", "tyrunt", "tyrantrum", "amaura",
    "aurorus", "sylveon", "hawlucha", "dedenne", "carbink", "goomy",
    "sliggoo", "goodra", "klefki", "phantump", "trevenant", "pumpkaboo",
    "gourgeist", "bergmite", "avalugg", "noibat", "noivern", "xerneas",
    "yveltal", "zygarde", "diancie", "hoopa", "volcanion",

    # Geração 7 - Alola
    "rowlet", "dartrix", "decidueye", "litten", "torracat", "incineroar",
    "popplio", "brionne", "primarina", "pikipek", "trumbeak", "toucannon",
    "yungoos", "gumshoos", "grubbin", "charjabug", "vikavolt", "crabrawler",
    "crabominable", "oricorio", "cutiefly", "ribombee", "rockruff", "lycanroc",
    "wishiwashi", "wishiwashi", "mareanie", "toxapex", "sandreel", "sandygast",
    "palossand", "pyukumuku", "type-null", "silvally", "minior", "komala",
    "turtonator", "togedemaru", "mimikyu", "bruxish", "drampa", "dhelmise",
    "jangmo-o", "hakamo-o", "kommo-o", "tapu-koko", "tapu-lele", "tapu-bulu",
    "tapu-fini", "nihilego", "buzzwole", "pheromosa", "xurkitree", "zeraora",
    "celesteela", "kartana", "guzzlord", "necrozma", "dusk-form-necrozma",
    "dawn-form-necrozma", "ultra-necrozma", "marshadow", "poipole", "naganadel",
    "stakataka", "blacephalon", "zeraora",

    # Geração 8 - Galar
    "grookey", "thwackey", "rillaboom", "scorbunny", "raboot", "cinderace",
    "sobble", "drizzile", "inteleon", "skwovet", "greedent", "rookidee",
    "corvisquire", "corviknight", "blipbug", "dottler", "orbeetle", "nickit",
    "thievul", "gossifleur", "eldegoss", "wooloo", "dubwool", "chewtle",
    "drednaw", "yamper", "boltund", "roolet", "flapple", "appletun",
    "silicobra", "sandaconda", "cramorant", "arrokuda", "rillaboom", "duraludon",
    "falinks", "pincurchin", "snom", "frosmoth", "stonjourner", "eiscue",
    "indeedee", "morpeko", "cufant", "copperajah", "dracozolt", "arctozolt",
    "dracovish", "arctovish", "duraludon", "eternatus", "kubfu", "urshifu",
    "zarude", "regieleki", "regidrago", "glastrier", "spectrier", "calyrex",

    # Geração 9 - Paldea
    "sprigatito", "floragato", "meowscarada", "Fuecoco", "Crocalor", "Skeledirge",
    "Quaxly", "Wiglett", "Wugtrio", "Dondozo", "Tatsugiri", "Oinkologne",
    "Tinkaton", "Bellibolt", "Pawmi", "Pawmo", "Pawmot", "Kilowattrel",
    "Bombirdier", "Toedscruel", "Nymble", "Lokix", "Clodsire", "Dudunsparce",
    "Tinkaton", "Great Tusk", "Scream Tail", "Brute Bonnet", "Flutter Mane",
    "Sandy Shocks","sandy shocks", "scream tail", "brute bonnet", "flutter mane", "great tusk",
    "roaring moon", "iron treads", "iron bundle", "iron valiant", "chi-yu",
    "chien-pao", "tatsugiri", "koraidon", "miraidon", "wo-chien", "ting-lu",
    "xurkitree", "zeraora"]